# Export workflow pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest
steps:
- bash: |
    echo "##vso[build.updatebuildnumber]$(Build.BuildNumber)-$(projectName)"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Update Build Number'

- script: |
    HOSTNAME=`yq -e ".tenant.hostname" configs/dev.yml`
    echo "##vso[task.setvariable variable=source_environment_hostname]${HOSTNAME}"
    echo $(source_environment_hostname)

    PORT=`yq -e ".tenant.port" configs/dev.yml`
    EXPORTER_USERNAME=`yq -e ".tenant.exporter_username" configs/dev.yml`

    echo "##vso[task.setvariable variable=source_environment_port]${PORT}"
    echo "##vso[task.setvariable variable=(exporter_username)]${EXPORTER_USERNAME}"
    PROJECTNAME=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$PROJECTNAME")

    echo ${HOSTNAME}
    echo ${PORT}

    echo ${PROJECTNAME}
    echo ${WORKFLOWID}

    echo $(source_environment_hostname)



    LOCAL_DEV_URL=https://${source_environment_hostname}:${source_environment_port}
    echo ${LOCAL_DEV_URL}
    EXPORT_URL=${LOCAL_DEV_URL}/apis/v1/rest/projects/${PROJECTNAME}/workflows/${WORKFLOWID}/export
    echo ${EXPORT_URL}
    echo ${PWD}

  displayName: 'Get Environment Tenant Details'

- script: | 
    curl --location --request POST ${EXPORT_URL} \
    --header 'Content-Type: application/json' \
    --header 'Accept: application/json' \
    -u $(exporter_username):$(exporter_password) \
    --data-raw '{
    "name": "Workflow_A",
    "description": "Something"
    }'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Export Workflow'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
