# Export workflow pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
  - repository: webMethodsIO_Integration
    type: git
    name: webMethodsIO_Integration/webMethodsIO_Integration
    ref: dev
    trigger:
    - dev

pool:
  vmImage: ubuntu-latest

steps:
- script: 
    echo ${projectName}
    echo ${workflowID}
    echo ${LOCAL_DEV_URL}
    EXPORT_URL=${LOCAL_DEV_URL}/apis/v1/rest/projects/:project/workflows/:workflow/export
    echo ${EXPORT_URL}
  displayName: 'Export Workflow'

- checkout: webMethodsIO_Integration

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
