# Testing pipeline

trigger:
- none

pool:
  vmImage: ubuntu-latest
resources:
  pipelines:
  - pipeline: play
    source: synchronizeToFeatureBranch
    trigger: true
    
  - pipeline: dev
    source: sychronizeToDEV
    trigger: true

  repositories:
  - repository: projectRepo
    type: github
    endpoint: github
    name: $(repoPath)
    ref: $(branch)
steps:
- checkout: projectRepo
  submodules: "true"
  persistCredentials: "true"
  clean: "true"
  path: $(repoName)
- checkout: self
  submodules: "true"
  persistCredentials: "true"
  clean: "true"
  path: self
  
- bash: |
    cd ../self
    source=$(echo $(resources.triggeringAlias))
    
    if [ -z "$source" ]; then
      source=$(echo $(environment))
      echo "##vso[task.setvariable variable=source_type]${source}"
    else
      echo "##vso[task.setvariable variable=source_type]$(resources.triggeringAlias)"
    fi
    echo $(System.DefaultWorkingDirectory)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Get Environment Tenant Details'

- script: |
    cd ../$(repoName)
    newman run ./resources/test/wmio_test.json -e ./resources/test/environments/$(source_type).json --reporters cli,junit --reporter-junit-export $(System.DefaultWorkingDirectory)/$(source_type)/results/junitReport.xml
    ls -ltr $(System.DefaultWorkingDirectory)/$(source_type)/results/
  displayName: 'Run newman'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/$(source_type)/results'
    failTaskOnFailedTests: true
    testRunTitle: '$(source_type) Test Run'