# Export workflow pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest
steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"
  clean: "true"
  path: self

- bash: |
    pwd
    ls -ltr
    cd self
    ls -ltr
    ls -ltr ./pipelines/
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Check Location'
- task: Bash@3
  inputs:
    filePath: './pipelines/scripts/loadCofig.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    failOnStderr: true
  displayName: 'Get Environment Tenant Details'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cd ../
      mkdir -p projectRepo
      cd projectRepo
      touch README.md
      git init
      git add README.md
      git commit -m "first commit"
      git remote add origin chini007@github.com:chini007/$(repoName).git
      git push -u origin master
      echo 'Hello world'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    failOnStderr: true
    
