tenant:
  hostname: "refplatformtest01.int-az-eu.webmethods.io"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "srini"                     # webMthodsIO Integration user  
  type: "qa"                                         #QA